name       : rocm-cmake
version    : 3.0.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocm-cmake/archive/roc-3.0.0.tar.gz : 9393fd534a100e8da55f44d0625337d76f3c7890e0297fe690c9e7d384b205ef
license    : MIT
component  : programming.devel
summary    : ROCM cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
description: |
    ROCM cmake modules provides cmake modules for common build tasks needed for the ROCM software stack.
setup      : |
    mkdir -p build/bin
    cd build
    cmake -DCMAKE_INSTALL_PREFIX=bin ..
install    : |
    cd build
    cmake --build . --target install

    install -Dm00644 bin/share/rocm/cmake/ROCMAnalyzers.cmake $installdir/usr/share/rocm/ROCMAnalyzers.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMCreatePackage.cmake $installdir/usr/share/rocm/ROCMCreatePackage.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMInstallTargets.cmake $installdir/usr/share/rocm/ROCMInstallTargets.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMSetupVersion.cmake $installdir/usr/share/rocm/ROCMSetupVersion.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMInstallSymlinks.cmake $installdir/usr/share/rocm/ROCMInstallSymlinks.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMPackageConfigHelpers.cmake $installdir/usr/share/rocm/ROCMPackageConfigHelpers.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMClangTidy.cmake $installdir/usr/share/rocm/ROCMClangTidy.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMConfig.cmake $installdir/usr/share/rocm/ROCMConfig.cmake
    install -Dm00644 bin/share/rocm/cmake/ROCMCppCheck.cmake $installdir/usr/share/rocm/ROCMCppCheck.cmake

 
