name       : rocm_bandwidth_test
version    : 3.3.0
release    : 4
source     :
    - https://github.com/RadeonOpenCompute/rocm_bandwidth_test/archive/rocm-3.3.0.tar.gz : f5f914073018619dc91662d5bf630903dfa4db9136d603591917fdfb3c9164ce
license    : Open Source License
component  : programming.devel
summary    : RocBandwidthTest is designed to capture the performance characteristics of buffer copying and kernel read/write operations. The help screen of the benchmark shows various options one can use in initiating cop/read/writer operations. In addition one can also query the topology of the system in terms of memory pools and their agents
description: |
    RocBandwidthTest is designed to capture the performance characteristics of buffer copying and kernel read/write operations. The help screen of the benchmark shows various options one can use in initiating cop/read/writer operations. In addition one can also query the topology of the system in terms of memory pools and their agents
builddeps  :
    - ROCT
    - ROCT-devel
    - ROCR
    - ROCR-devel
setup      : |
    mkdir -p build
    cd build
    %cmake -DCMAKE_PREFIX_PATH=. ..
build      : |
    cd build
    %make
install    : |
    cd build
    mkdir -p $installdir/usr/bin
    install -Dm00755 rocm-bandwidth-test $installdir/usr/bin/rocm_bandwidth_test
