name       : llvm-roc
version    : 3.3.0
release    : 4
source     :
    - https://github.com/RadeonOpenCompute/llvm-project/archive/rocm-ocl-3.3.0.tar.gz : a2bef7042e8e2f2cd8548cb246b88322e1c77188839983dcac8312d56f544dc8
license    : Apache License 2.0
component  : programming.devel
summary    : "ROCm llvm,lld,clang"
description: |
    "ROCm llvm,lld,clang"
clang      : yes
builddeps  :
    - git
    - libedit
    - libedit-devel
    - ocaml
    - findlib
    - ROCR
    - ROCR-devel
    - swig
    - z3
    - z3-devel
setup      : |
    mkdir -p build

build      : |
    ls
    ls ../
    cd build
    %cmake -G Ninja -DLLVM_USE_LINKER=lld -D_FORTIFY_SOURCE=0 -DLLVM_ENABLE_PROJECTS='clang;libcxx;libcxxabi;lld' -DCMAKE_INSTALL_PREFIX=%libdir%/rocm/llvm -DCMAKE_BUILD_TYPE=RelWithDebInfo ../llvm

install    : |
    cd build
    %cmake --build -DCMAKE_INSTALL_PREFIX=%libdir%/rocm/llvm .
    ls
    export 'CFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -D_FORTIFY_SOURCE=0 -Wformat -Wformat-security -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT'
    export 'CXXFLAGS=-mtune=generic -march=x86-64 -g2 -O2 -pipe -fPIC -D_FORTIFY_SOURCE=0 -fstack-protector-strong --param ssp-buffer-size=32 -fasynchronous-unwind-tables -ftree-vectorize -feliminate-unused-debug-types -Wall -Wno-error -Wp,-D_REENTRANT'


    DESTDIR=/home/build/YPKG/root/llvm-roc/install
    DESTDIR=$installdir/rocm %ninja_install -j24 -C .
