name       : z3
version    : 4.8.7
release    : 2
source     :
    - https://github.com/Z3Prover/z3/archive/z3-4.8.7.tar.gz : 8c1c49a1eccf5d8b952dadadba3552b0eac67482b8a29eaad62aa7343a0732c3
license    : MIT
component  : programming.devel
summary    : Z3 is a theorem prover from Microsoft Research.
description: |
    Z3 is a theorem prover from Microsoft Research.
builddeps  :
    - pkgconfig(python3)
setup      : |
    mkdir -p build
    cd build
    %cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_PYTHON_BINDINGS=0 -DCMAKE_INSTALL_LIBDIR=lib64
build      : |
    cd build
    %make -j6
install    : |
    cd build
    %make_install
