name       : ROCm-Device-Libs
version    : 3.3.0
release    : 4
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/rocm-ocl-3.3.0.tar.gz : 706b08230790e08ca6a7a2fb7687d6131fd39a562148340e00fa37a6c06769c5
license    : Open Source License
component  : programming.devel
summary    : ROCm Device libraries.
clang      : yes
description: |
    ROCm Device libraries.
builddeps  :
    - cmake
    - rocm-cmake
    - ROCR
    - ROCR-devel
    - ROCR
    - ROCR-devel
    - libstdc++
    - libgcc
    - llvm-roc
    - z3
    - z3-devel
setup      : |
    mkdir -p build
build      : |

    cd build
    export LLVM_BUILD=%libdir%/rocm/llvm
    CC=$LLVM_BUILD/bin/clang %cmake -DLLVM_DIR=$LLVM_BUILD ..
    %make

install    : |
    cd build
    export LLVM_BUILD=%libdir%/rocm/llvm
    export CC=$LLVM_BUILD/bin/clang
    CC=$LLVM_BUILD/bin/clang %make_install ../
