name       : ROCm-Device-Libs
version    : 3.0.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/ROCm-Device-Libs/archive/roc-ocl-3.0.0.tar.gz : 3bb3c6e3be39a9e9dcf616d71f5414014a4c1aa17ff8145baafaf99300241928
license    : Open Source License
component  : programming.devel
summary    : ROCm Device libraries.
description: |
    ROCm Device libraries.
builddeps  :
    - ROCR
    - ROCR-devel
    - ROCR
    - ROCR-devel
    - llvm-roc
    - z3
    - z3-devel
setup      : |
    mkdir -p build
    cd build
build      : |
    ls /usr/lib64/llvm
    export LLVM_BUILD=%libdir%/llvm/roc-2.10.0
    CC=$LLVM_BUILD/bin/clang %cmake -DLLVM_DIR=$LLVM_BUILD 
install    : |
    %make_install
