name       : rocminfo
version    : 3.0.0
release    : 2
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/roc-3.0.0.tar.gz : 2e3f9613461b1d8f335f135e3b2edb6b0ce5c9d3a3b2cfa9b7a3456273a73840
license    : Open Source License (NCSA)
component  : programming.devel
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - ROCT
    - ROCT-devel
    - ROCR
    - ROCR-devel
setup      : |
    mkdir -p build
    cd build
    %cmake -DROCM_DIR=/usr -DROCRTST_BLD_TYPE=Release -DROCRTST_BLD_BITS=64 ..
build      : |
    cd build
    make
install    : |
    cd build
    mkdir -p $installdir/usr/bin
    install -Dm00755 rocminfo $installdir/usr/bin/rocminfo
    install -Dm00755 rocm_agent_enumerator $installdir/usr/bin/rocm_agent_enumerator
