name       : rocminfo
version    : 3.3.0
release    : 4
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/rocm-3.3.0.tar.gz : e666f662c9e465aaabbbd0b109d87e017243cdf1a0898fabf5a90947bb3dbcd7
license    : Open Source License (NCSA)
component  : programming.devel
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - rocm-cmake
    - ROCT
    - ROCT-devel
    - ROCR
    - ROCR-devel
setup      : |
    mkdir -p build
    cd build
    %cmake -DROCM_DIR=/usr -DROCRTST_BLD_TYPE=Release -DROCRTST_BLD_BITS=64 ..
build      : |
    cd build
    make
install    : |
    cd build
    mkdir -p $installdir/usr/bin
    install -Dm00755 rocminfo $installdir/usr/bin/rocminfo
    install -Dm00755 rocm_agent_enumerator $installdir/usr/bin/rocm_agent_enumerator
