name       : rocminfo
version    : 2.7.0
release    : 1
source     :
    - https://github.com/RadeonOpenCompute/rocminfo/archive/roc-2.7.0.tar.gz : 5f7ec4665c4100e69c4216cee3974f03d1017311f9d297ef7c9cf3b58e7edb0f
license    : Open Source License (NCSA)
component  : programming.devel
summary    : ROCm Application for Reporting System Info
description: |
    ROCm Application for Reporting System Info
builddeps  :
    - ROCT
    - ROCT-devel
    - ROCR
    - ROCR-devel
setup      : |
    %patch -p1 < $pkgfiles/01_arraysize.patch
    mkdir -p build
    cd build
    %cmake -DROCM_DIR=/usr -DROCRTST_BLD_TYPE=Release -DROCRTST_BLD_BITS=64 ..
build      : |
    cd build
    make
install    : |
    cd build
    mkdir -p $installdir/usr/bin
    install -Dm00755 rocminfo $installdir/usr/bin/rocminfo
    install -Dm00755 rocm_agent_enumerator $installdir/usr/bin/rocm_agent_enumerator
