name       : findlib
version    : 1.8.0
release    : 1
source     :
    - http://download.camlcity.org/download/findlib-1.8.0.tar.gz : 2b7b7d6d65bb0f3f8a2c51c63c02b0bcf1fea4c23513f866140dc7dc24fe27ad
license    : MIT
component  : programming.devel
summary    : Findlib is a library manager for Objective Caml. It provides a convention how to store libraries, and a file format ("META") to describe the properties of libraries. There is also a tool (ocamlfind) for interpreting the META files, so that it is very easy to use libraries in programs and scripts.
description: |
    Findlib is a library manager for Objective Caml. It provides a convention how to store libraries, and a file format ("META") to describe the properties of libraries. There is also a tool (ocamlfind) for interpreting the META files, so that it is very easy to use libraries in programs and scripts.
builddeps  :
    - ocaml
    - ocamlbuild
setup      : |
    ./configure -bindir /usr/bin \
                -mandir /usr/share/man \
                -sitelib %libdir%/ocaml \
                -config /etc/findlib/findlib.conf \
                -no-custom
build      : |
    %make all
install    : |
    %make_install
