name       : findlib
version    : 1.8.1
release    : 2
source     :
    - http://download.camlcity.org/download/findlib-1.8.1.tar.gz : 8e85cfa57e8745715432df3116697c8f41cb24b5ec16d1d5acd25e0196d34303
license    : MIT
component  : programming.devel
summary    : Findlib is a library manager for Objective Caml. It provides a convention how to store libraries, and a file format ("META") to describe the properties of libraries. There is also a tool (ocamlfind) for interpreting the META files, so that it is very easy to use libraries in programs and scripts.
description: |
    Findlib is a library manager for Objective Caml. It provides a convention how to store libraries, and a file format ("META") to describe the properties of libraries. There is also a tool (ocamlfind) for interpreting the META files, so that it is very easy to use libraries in programs and scripts.
clang: yes
builddeps  :
    - ocaml
    - ocamlbuild
rundeps    :
    - ocaml
    - ocamlbuild
setup      : |
    ./configure -bindir $installdir/usr/bin \
                -mandir $installdir/usr/share/man \
                -sitelib $installdir/usr/lib64/ocaml \
                -config $installdir/etc/findlib/findlib.conf \
                -no-custom
    cat Makefile.config
    %patch < $pkgfiles/01_destdir.patch
build      : |
    %make all
install    : |
    cat Makefile.config
    %make_install
