name       : rocm-comgr
version    : 3.3.0
release    : 4
source     :
    - https://github.com/RadeonOpenCompute/ROCm-CompilerSupport/archive/rocm-3.3.0.tar.gz : 01e2524e0f28ecd6f46c9720f279207de935d826b0172158792aa3ec86af9ca7
license    : Apache License 2.0
component  : programming.devel
summary    : "ROCm llvm,lld,clang"
description: |
    "ROCm comgr"
clang      : yes
builddeps  :
    - llvm-roc
    - ROCm-Device-Libs
    - ROCm-Device-Libs-devel
    - z3
    - z3-devel
setup      : |
    cd lib/comgr
    %patch < $pkgfiles/01_clangpath.patch
    %patch < $pkgfiles/02_dependencies.patch
    %patch < $pkgfiles/03_findlldincludes.patch
    %patch -v < $pkgfiles/04_rocm_in_lib64_not_opt.patch
    mkdir -p build
build      : |
    cd lib/comgr/build
    export LLVM_BUILD=%libdir%/rocm/llvm
    cmake -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_PREFIX_PATH="LLVM_BUILD;$LLVM_BUILD/lib/cmake/clang" \
        -DClang_DIR=$LLVM_BUILD/lib/cmake/clang \
         ..
install    : |
    cd lib/comgr/build

    %make_install
